clicker1: clicker1.c
	gcc -o $@ $^ -std=c11 -g

example1: example1.c
	gcc -o $@ $^ -std=c11

problem1: problem1.c
	gcc -o $@ $^ -std=c11

move_around: move_around.c
	gcc -o $@ $^ -std=c11 -g

problem2: problem2.c
	gcc -o $@ $^ -std=c11 -g
